In [1]:
import numpy as np

#A 1D array of integers from 10 to 19
arr = np.arange(10, 20)
print(arr)  

[10 11 12 13 14 15 16 17 18 19]


In [2]:
arr_2D = np.full((4, 3), 1.5)
print(arr_2D)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [ ]:
arr_zeros = np.zeros((2, 2, 3))
print(arr_zeros)   


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
#Convert the 2D array of floats to integers
arr_2D_int =arr_2D.astype(int)
print(arr_2D_int)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#Question 2
import numpy as np

sales = np.array([
    [120, 135, 110, 145, 130],  # Region A
    [ 90,  85,  95, 100, 110],  # Region B
    [200, 215, 190, 225, 245],  # Region C
    [155, 140, 135, 160, 170]   # Region D
])
regions = np.array(["A", "B", "C", "D"])
quarters = np.array(["Q1", "Q2", "Q3", "Q4", "Q5"])

#Select all quarters for Regiona B
region_b_sales = sales[1, :]
print("Sales for Region B:", region_b_sales)

# Q2_Q4 sales for all regions
q2_q4_sales = sales[:, 1:4]
print("Q2 to Q4 sales for all regions:\n", q2_q4_sales)

#Select Q5 sales for Regions A and D only (use slicing or fancy indexing).
#Q5 is the last column, so we can use index 4 for that. Regions A and D are the first and fourth rows, so we can use indices 0 and 3.
q5_sales_a_d = sales[[0, 3], 4]
print("Q5 sales for Regions A and D:", q5_sales_a_d)    


Sales for Region B: [ 90  85  95 100 110]
Q2 to Q4 sales for all regions:
 [[135 110 145]
 [ 85  95 100]
 [215 190 225]
 [140 135 160]]
Q5 sales for Regions A and D: [130 170]


In [ ]:
#Compute the shape of each result and add a brief comment: “Is this 1D or 2D, and why?”
print("Shape of Region B sales:", region_b_sales.shape)  # This is a 1D array because it contains sales data for a single region across multiple quarters.
print("Shape of Q2 to Q4 sales:", q2_q4_sales.shape)  # This is a 2D array because it contains sales data for multiple regions across multiple quarters.
print("Shape of Q5 sales for Regions A and D:", q5_sales_a_d.shape)  # This is a 1D array because it contains sales data for two specific regions for

In [9]:
names = np.array(["Ana", "Ben", "Chen", "Dana", "Eli", "Fatima", "George", "Hui"])
spend = np.array([200, 150, 300, 120, 180, 220, 160, 310])      # marketing spend
revenue = np.array([400, 180, 500, 100, 220, 260, 150, 600])   # revenue

#Compute the ROI for each person: roi = revenue / spend
roi = revenue / spend
print("ROI for each person:", roi)  


ROI for each person: [2.         1.2        1.66666667 0.83333333 1.22222222 1.18181818
 0.9375     1.93548387]


In [10]:
roi_mask = roi >= 2.0
high_roi_names = names[roi_mask]
print("People with ROI >= 2.0:", high_roi_names)

#List their spend and revenue as well
high_roi_spend = spend[roi_mask]
high_roi_revenue = revenue[roi_mask]
print("Spend for people with ROI >= 2.0:", high_roi_spend)
print("Revenue for people with ROI >= 2.0:", high_roi_revenue)

People with ROI >= 2.0: ['Ana']
Spend for people with ROI >= 2.0: [200]
Revenue for people with ROI >= 2.0: [400]


In [12]:
spend_mask = spend >= 200
high_spend_names = names[spend_mask]
print("People with spend >= 200:", high_spend_names)

roi_and_spend_mask = (roi >= 2.0) & (spend >= 200)
high_roi_and_spend_names = names[roi_and_spend_mask]
print("People with ROI >= 2.0 and spend >= 200:", high_roi_and_spend_names)

People with spend >= 200: ['Ana' 'Chen' 'Fatima' 'Hui']
People with ROI >= 2.0 and spend >= 200: ['Ana']


In [17]:
students = np.array(["S1", "S2", "S3", "S4", "S5"])
subjects = np.array(["Math", "Stats", "Python"])

scores = np.array([
    [75, 80, 85],
    [60, 65, 70],
    [90, 88, 92],
    [82, 79, 84],
    [70, 72, 78]
])

scores_avg_student = scores.mean(axis=1)
print("Average score for each student:", scores_avg_student)
scores_avg_subject = scores.mean(axis=0)
print("Average score for each subject:", scores_avg_subject)
scores_centered = scores - scores_avg_subject
print("Centered scores:\n", scores_centered)

#compare which student looks best by raw average vs centered average
print("Raw Averages:", scores_avg_student)
print("Centered Averages:", scores_centered.mean(axis=1))


Average score for each student: [80.         65.         90.         81.66666667 73.33333333]
Average score for each subject: [75.4 76.8 81.8]
Centered scores:
 [[ -0.4   3.2   3.2]
 [-15.4 -11.8 -11.8]
 [ 14.6  11.2  10.2]
 [  6.6   2.2   2.2]
 [ -5.4  -4.8  -3.8]]
Raw Averages: [80.         65.         90.         81.66666667 73.33333333]
Centered Averages: [  2.         -13.          12.           3.66666667  -4.66666667]


In [19]:
daily_visits = np.array([
    120, 130, 125, 140, 150,
    160, 170, 155, 145, 135,
    128, 132, 138, 142, 148,
    152, 158, 162, 168, 172,
    180, 190, 185, 175, 165,
    155, 145, 135, 125, 115
])

weekly_visits = daily_visits.reshape(6, 5) # Reshape to 6 weeks (rows) and 5 days (columns)
print("Weekly visits:\n", weekly_visits)

weekly_visits = weekly_visits.sum(axis=1)  # Sum across columns to get total visits per week
print("Total visits per week:", weekly_visits)

Weekly visits:
 [[120 130 125 140 150]
 [160 170 155 145 135]
 [128 132 138 142 148]
 [152 158 162 168 172]
 [180 190 185 175 165]
 [155 145 135 125 115]]
Total visits per week: [665 765 688 812 895 675]


In [ ]:
avg_day_of_week = weekly_visits.mean(axis=0)
print("Average visits per day of the week:", avg_day_of_week)

Average visits per day of the week: 750.0


In [22]:
# Flatten
original_shape = weekly_visits.flatten()
print("Back to original match?", np.array_equal(daily_visits, original_shape))

Back to original match? False
