# Lesson 1.6: Introduction to NumPy

## Introduction
**NumPy**, short for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

Many computational and data science packages use NumPy as the main building block. It is a fundamental library for scientific computing in Python.

### Key Features of NumPy:
* **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.
* **Vectorization**: Mathematical functions for fast operations on entire arrays of data without having to write loops.
* **Linear Algebra**: Tools for random number generation, Fourier transforms, and matrix manipulation.
* **C API**: For connecting NumPy with libraries written in C, C++, or FORTRAN.

### Advantages over Python Lists:
1. **Contiguous Memory**: NumPy internally stores data in a contiguous block of memory, independent of other built-in Python objects. This allows for significantly faster access and manipulation.
2. **Vectorized Operations**: NumPy algorithms written in C can operate on this memory without type checking or other Python overhead, performing complex computations without slow `for` loops.

![numpy_vs_list](../assets/numpy_vs_python_list.png)

## Part 1: Performance Benchmark
To give you an idea of the performance difference, consider a NumPy array of one million integers and an equivalent Python list. We use the `%timeit` magic command to measure execution time.

In [2]:
import numpy as np

# np.arrange() create a NumPy array with values from 0 to 999,999
# '_' is the separator for better readability
my_arr = np.arange(1_000_000)
# Creates a Python list with values from 0 to 999,999
my_list = list(range(1_000_000))

print("NumPy Vectorized Multiplication (my_arr * 2):")
# timeit - Jupyter command 
%timeit my_arr2 = my_arr * 2

print("\nPython List Comprehension ([x * 2 for x in my_list]):")
%timeit my_list2 = [x * 2 for x in my_list]

NumPy Vectorized Multiplication (my_arr * 2):
1.41 ms ± 172 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

Python List Comprehension ([x * 2 for x in my_list]):
41.7 ms ± 1.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


Interpretation of results:
- NumPy operation took 1.45 ms while Python list operation took 67.9 ms (40 times)
- 1ms = 1000 microseconds


In [3]:
#to check on function on what it does, mouse over the function name or type the help()
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)
    
    Return evenly spaced values within a given interval.
    
    ``arange`` can be called with a varying number of positional arguments:
    
    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.
    
    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.
    
    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.
    
    S

In [4]:
import sys
print("Python location:", sys.executable)
print("Pyton version:", sys.version)

Python location: /home/shuhp/miniconda3/envs/pds/bin/python
Pyton version: 3.10.20 (main, Mar 11 2026, 17:46:40) [GCC 14.3.0]


## Part 2: The ndarray (N-dimensional array)
The `ndarray` is a fast, flexible container for large datasets. It is a multidimensional array of fixed size with **homogeneous** elements (all elements must be of the same type).

Every array has:
* **shape**: A tuple indicating the size of each dimension.
* **dtype**: An object describing the data type of the array.
* **ndim**: The number of dimensions (axes).

### ndarray illustration
![ndarray](../assets/numpy_ndarray.png)

In [5]:
# [DEMO] Creating arrays from sequences
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

print(f"Array 1:\n{arr1}")
print(f"Shape: {arr1.shape}, Dtype: {arr1.dtype}, Dimensions: {arr1.ndim}")

data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

print(f"Array 2:\n{arr2}")
print(f"Shape: {arr2.shape}, Dtype: {arr2.dtype}, Dimensions: {arr2.ndim}")

# shape (rows, columns)

Array 1:
[6.  7.5 8.  0.  1. ]
Shape: (5,), Dtype: float64, Dimensions: 1
Array 2:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4), Dtype: int64, Dimensions: 2


In [6]:
# Jagged arrays and rectangluar requirement
Jagged_data = [
    [1,2,3],
    [4,5]
]
# Jagged_arr = np.array(jagged_data)
jagged_arr_obj = np.array(Jagged_data, dtype=object)
print(f"Jagged Array (dtype=object):\n{jagged_arr_obj}")
print(f"Shape: {jagged_arr_obj.shape}, Dtype: {jagged_arr_obj.dtype}, Dimensions: {jagged_arr_obj.ndim}")

Jagged Array (dtype=object):
[list([1, 2, 3]) list([4, 5])]
Shape: (2,), Dtype: object, Dimensions: 1


### Data Types and Casting
NumPy supports specific numerical types like `int32`, `float64`, etc. You can explicitly convert an array from one `dtype` to another using the `astype` method.

**Note:** If you cast floating-point numbers to an integer `dtype`, the decimal part will be truncated.

In [7]:
# [DEMO] Casting arrays
arr = np.array([3.7, -1.2, 0.5, 12.9])
print("Original:", arr)
# cast the dataype using astype
print("Casted to int32:", arr.astype(np.int32))

Original: [ 3.7 -1.2  0.5 12.9]
Casted to int32: [ 3 -1  0 12]


### 🛠️ Exercise 1: Creation & Casting
1. Create a 3x4 array of all ones using `np.ones()`.
2. Cast this array to `float32`.
3. Create an array of strings representing numbers: `['1.25', '-9.6', '42']`. Cast it to `float`.

In [8]:
# Create a 3x4 of one array
arr2 = np.ones((3, 4))
print("Original", arr2)
ones_array_float32 = arr2.astype(np.float32)
print("Casted to float32", ones_array_float32.dtype)

arr3 = np.array(['1.25', '9.6', '42'])
arr3_array_float = arr3.astype(float)
print("Original string Array:", arr3)
print("Casted to Float Array:", arr3_array_float)
print("Casted to float", arr3_array_float.dtype)

Original [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Casted to float32 float32
Original string Array: ['1.25' '9.6' '42']
Casted to Float Array: [ 1.25  9.6  42.  ]
Casted to float float64


In [9]:
zeroes_array = np.zeros((2,5))
print("2x5 Array of Zeros:\n", zeroes_array)

full_array = np.full((3,3), 7)
print("3x3 Array filled with 7:\n", full_array)

2x5 Array of Zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3x3 Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


In [10]:
#try to change value of element
zeroes_array[0,0] = 5
print("Modified Array:\n", zeroes_array)

Modified Array:
 [[5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
#try change value of element to other type
full_array [0,0] = 3.5
print("Modified full Array:\n", full_array)
print("Dtype after modification:\n", full_array.dtype)

# Print(f) - embeded value in string
# print(f"")
# f-strings allow you to embed expressions inside string literals, using curly braces {}.
# The expressions inside the curly braces are evaluated at runtime and then formatted using the __format__ protocol. This makes it easy to include variable values or even complex expressions directly within a string without needing to concatenate strings or use the older .format() method.
# Example:
name = "Alice"
age = 30
print(f"{name} is {age} years old.")    

Modified full Array:
 [[3 7 7]
 [7 7 7]
 [7 7 7]]
Dtype after modification:
 int64
Alice is 30 years old.


In [12]:
# performance difference between data types
arr_64 = np.arange(1_000_000, dtype=np.float64)    
arr_32 = np.arange(1_000_000, dtype=np.float32)

print("Performance of float64 array multiplication:")
%timeit arr_64 * 2

print("\nPerformance of float32 array multiplication:")
%timeit arr_32 * 2

print("Memory usage of float64 array:", arr_64.nbytes / 1024 / 1024, "MB")
print("Memory usage of float32 array:", arr_32.nbytes / 1024 / 1024, "MB")

Performance of float64 array multiplication:


1.14 ms ± 60.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Performance of float32 array multiplication:
358 μs ± 47.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
Memory usage of float64 array: 7.62939453125 MB
Memory usage of float32 array: 3.814697265625 MB


## Part 3: Arithmetic & Broadcasting
Arithmetic operations are applied as batch operations without for loops. **Broadcasting** describes how arithmetic works between arrays of different shapes.

![vectorization](../assets/vectorization.png)

Example: A scalar value being replicated (broadcast) to match the shape of a larger array.

In [13]:
# [DEMO] Arithmetic & Broadcasting
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
# 1x1, 2x2 etc
print("Element-wise multiplication (arr * arr):\n", arr * arr)
print("\nBroadcasting scalar (1 / arr):\n", 1 / arr)

Element-wise multiplication (arr * arr):
 [[ 1.  4.  9.]
 [16. 25. 36.]]

Broadcasting scalar (1 / arr):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [14]:
print("Adding scalar to array (arr + 10):\n", arr + 10) 

Adding scalar to array (arr + 10):
 [[11. 12. 13.]
 [14. 15. 16.]]


## Part 4: Indexing and Slicing
One-dimensional arrays act similarly to Python lists. In 2D arrays, indexing can be done with `[row, column]` syntax. 

### 2D Array Indexing Syntax
![2d_array_indexing](../assets/ndarray_axis_index.png)

**Important:** Array slices are **views** on the original array. This means data is not copied, and modifications to the slice will be reflected in the source array.

In [15]:
# [DEMO] Slicing views
arr = np.arange(10)
print("Original array:", arr)
# [start:stop] - slice from start index to stop index (exclusive)
# [start:stop:step] - slice from start index to stop index (exclusive) with step
# [0:10:1] is the same as [0:10] - start at 0 to 9.
arr_slice = arr[5:8]
# able to copy the arange using arr[5:8].copy() to create a new array that is independent of the original. otherwise it updated the original array when we update the slice.    
print("Slice of array (arr[5:8]):", arr_slice)  
arr_slice[1] = 12345
print("Original array modified via slice:", arr)


Original array: [0 1 2 3 4 5 6 7 8 9]
Slice of array (arr[5:8]): [5 6 7]
Original array modified via slice: [    0     1     2     3     4     5 12345     7     8     9]


In [16]:
# [DEMO] 2D Slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# arr2d[row_slice, column_slice]
# start:stop:step, default 0:end:1
# :2 - first two rows - [1,2,3] and [4,5,6]
# 1: - columns from index 1 to end - [2,3] and [5,6]
print("\nFirst two rows, columns 1 onwards:\n", arr2d[:2, 1:])


First two rows, columns 1 onwards:
 [[2 3]
 [5 6]]


### 🛠️ Exercise 2: The Logic of Slicing
1. Select the first column of `arr2d` using a slice.
2. Set all values in the second row to 0.
3. **Socratic Prompt:** How does `arr2d[1]` differ from `arr2d[1, :]`? (Hint: check shapes)

In [17]:
# Your code here
arr2d_first_col = arr2d[:, :1]  
print("\nFirst column:\n", arr2d_first_col)

# modifying the first column of row 2.
print("\nFirst column after modification:\n", arr2d_first_col)
print("\nOriginal array after modification:\n", arr2d)



First column:
 [[1]
 [4]
 [7]]

First column after modification:
 [[1]
 [4]
 [7]]

Original array after modification:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# set all values in the second row to 0
arr2d[1] = 0
print("\nArray after setting second row to 0:\n", arr2d)


Array after setting second row to 0:
 [[1 2 3]
 [0 0 0]
 [7 8 9]]


## Part 5: Boolean Indexing
Like arithmetic operations, comparisons (such as `==`) with arrays are vectorized. This yields a boolean array which can be used to filter data.

In [19]:
# [DEMO] Filtering scores
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
scores = np.array([[75, 80], [85, 90], [95, 100], [100, 77], [85, 92], [95, 80], [72, 80]])

# A mask is a boolean array indicating which elements of the original array satisfy a certain condition.
bob_mask = (names == 'Bob')
print("Mask:", bob_mask)
print("Bob's scores:\n", scores[bob_mask])

Mask: [ True False False  True False False False]
Bob's scores:
 [[ 75  80]
 [100  77]]


### 🛠️ Exercise 3: Complex Filtering
1. Select all scores where the name is NOT 'Bob'.
2. Select scores for 'Bob' or 'Will' using the `|` operator.
3. Find all scores less than 80 and set them to 0.

In [20]:
print("\nNames:", names)
print("Scores:\n", scores)  

# Exercise 3.1
Not_bob_mask = (names != 'Bob')
print("Not Bob Mask:", Not_bob_mask)
print("Not Bob's scores:\n", scores[Not_bob_mask]) 

# Exercise 3.2
bob_or_will_mask = (names == 'Bob') | (names == 'Will')
print("Bob or Will Mask:", bob_or_will_mask)
print("Bob and Will scores:\n", scores[bob_or_will_mask])   



Names: ['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
Scores:
 [[ 75  80]
 [ 85  90]
 [ 95 100]
 [100  77]
 [ 85  92]
 [ 95  80]
 [ 72  80]]
Not Bob Mask: [False  True  True False  True  True  True]
Not Bob's scores:
 [[ 85  90]
 [ 95 100]
 [ 85  92]
 [ 95  80]
 [ 72  80]]
Bob or Will Mask: [ True False  True  True  True False False]
Bob and Will scores:
 [[ 75  80]
 [ 95 100]
 [100  77]
 [ 85  92]]


In [21]:
#Exercise 3.3
scores_copy = scores.copy()
score_less_80_mask = (scores_copy < 80).any(axis=1)
print("Scores less than 80 Mask:\n", score_less_80_mask)
scores_copy[score_less_80_mask] = 0
print("Scores after setting values less than 80 to 0:\n", scores_copy)

Scores less than 80 Mask:
 [ True False False  True False False  True]
Scores after setting values less than 80 to 0:
 [[  0   0]
 [ 85  90]
 [ 95 100]
 [  0   0]
 [ 85  92]
 [ 95  80]
 [  0   0]]


## Part 6: Universal Functions (ufuncs) and Methods
A **ufunc** is a function that performs element-wise operations on data in ndarrays. 

* **Unary ufuncs**: Take one array (e.g., `sqrt`, `exp`).
* **Binary ufuncs**: Take two arrays (e.g., `add`, `maximum`).
* **Statistical Methods**: `mean`, `sum`, `std` can be computed over the entire array or along an axis.

In [22]:
# [DEMO] Statistical Methods
# Create a 3x4 array of random numbers from a normal distribution
# arr = np.random.randn(3, 4)

print("Random Array:\n", arr)
# vertical axis=0 (col), horizontal axis=1 (row)
print("\nMean down rows (axis=0):", arr.mean(axis=0))
print("Sum across columns (axis=1):", arr.sum(axis=1))

Random Array:
 [    0     1     2     3     4     5 12345     7     8     9]

Mean down rows (axis=0): 1238.4


AxisError: axis 1 is out of bounds for array of dimension 1

## Part 7: Linear Algebra
Linear algebra operations, like matrix multiplication, are crucial for many data science algorithms. Multiplying two arrays with `*` is an element-wise product; for matrix multiplication, use `.dot()` or the `@` operator.

![matrix_multiplication](../assets/matrix_multiplication.png)

In [ ]:
# [DEMO] Matrix Multiplication
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[6, 23], [-1, 7], [8, 9]])

print("Matrix product (x @ y):\n", x @ y)

Matrix product (x @ y):
 [[ 28  64]
 [ 67 181]]


### 🛠️ Exercise 4: Reshaping & Statistics
1. Create an array of 15 integers using `arange(15)` and reshape it to `(3, 5)`.
2. Calculate the average value of each row.
3. Use `np.unique()` to find distinct elements in an array of your choice.
4. Transpose the reshaped array using `.T` and check the new shape.

In [ ]:
# reshape changes the shape of the array without changing its data. The new shape must be compatible with the original shape, meaning that the total number of elements must remain the same. For example, if you have an array with 15 elements, you can reshape it into a 3x5 array, but not into a 4x4 array (which would require 16 elements). Reshaping is useful for preparing data for machine learning models or for performing operations that require specific input shapes.
arr_15 = np.arange(15).reshape((3, 5))
print("Original Array:\n", arr_15)
print("Mean for rows (axis=1):", arr_15.mean(axis=1))

sample_arr = np.array([1, 2, 3, 2, 4, 1, 5])
print("Unique elements:", np.unique(sample_arr))
np.transpose(arr_15)

Original Array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Mean for rows (axis=1): [ 2.  7. 12.]
Unique elements: [1 2 3 4 5]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])